export const FETCH_GLOBAL_DATA_START = 'FETCH_GLOBAL_DATA_START';
export const FETCH_GLOBAL_DATA_SUCCESS = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_FAIL = 'FETCH_GLOBAL_DATA_FAIL';

export const FETCH_COUNTRY_DATA_START = 'FETCH_COUNTRY_DATA_START';
export const FETCH_COUNTRY_DATA_SUCCESS = 'FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_COUNTRY_DATA_FAIL = 'FETCH_COUNTRY_DATA_FAIL';

export const FETCH_HISTORY_BY_COUNTRY_START = 'FETCH_HISTORY_BY_COUNTRY_START';
export const FETCH_HISTORY_BY_COUNTRY_SUCCESS = 'FETCH_HISTORY_BY_COUNTRY_SUCCESS';
export const FETCH_HISTORY_BY_COUNTRY_FAIL = 'FETCH_HISTORY_BY_COUNTRY_FAIL';

export const FETCH_HISTORY_BY_DATE_START = 'FETCH_HISTORY_BY_DATE_START';
export const FETCH_HISTORY_BY_DATE_SUCCESS = 'FETCH_HISTORY_BY_DATE_SUCCESS';
export const FETCH_HISTORY_BY_DATE_FAIL = 'FETCH_HISTORY_BY_DATE_FAIL';