export const FETCH_GLOBAL_DATA_START = 'FETCH_GLOBAL_DATA_START';
export const FETCH_GLOBAL_DATA_SUCCESS = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_FAIL = 'FETCH_GLOBAL_DATA_FAIL';

export const FETCH_COUNTRY_DATA_START = 'FETCH_COUNTRY_DATA_START';
export const FETCH_COUNTRY_DATA_SUCCESS = 'FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_COUNTRY_DATA_FAIL = 'FETCH_COUNTRY_DATA_FAIL';

export const FETCH_HISTORY_START = 'FETCH_HISTORY_START';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL';

